### ISSUE TITLE
ESE 542 Ratings.

### ISSUE THREAD

**Issue by chukwudyre** [MyMCIT/MyMCIT#40]
Considering the recent name change for the ESE courses, it appears that some reviews originally attributed to course 542 are actually meant for course 541 (since 541 was previously named 542). To address this issue, one approach could involve identifying reviews submitted prior to the launch of the current version of course 542 and migrating only those reviews. For instance, reviews from the Fall 2021 semester 

Great job guys

**Comment by chaoticgoodpanda** [comment]
Thanks for this feedback. Do you happen to know the exact semester ESE 541 was named ESE 542? Was it indeed the Fall 2021 semester when it was first called ESE 542, or was that the last semester it was called ESE 541? Thanks!

**Comment by SteveMediev** [comment]
ESE 5420 Statistics for Data Science: An Applied Machine Learning Course was renamed ESE 5410 Machine Learning for Data Science after summer 2022. Thus, all the reviews from summer 2022 or earlier belong to ESE 5410 Machine Learning for Data Science.

Then the title of ESE 5420 should be changed to drop the subtitle "An Applied Machine Learning Course."

![5410 5420](https://github.com/MyMCIT/MyMCIT/assets/86175563/a14ab2c2-d318-41f2-9fdc-ffee814ec2af)

**Comment by chaoticgoodpanda** [comment]
Thanks for this, @SteveMediev ! Changes have been made and should propagate within 24 hours:

-  All reviews from Summer 2022 or earlier switched to 5410
- Title for 5420 revised to Statistics for Data Science
