### ISSUE TITLE
Fix review date of older reviews

### ISSUE THREAD

**Issue by qu8n** [MyMCIT/MyMCIT#44]
Hey team,

Just wanted to flag you that many, if not all, older reviews have a review date of "1/24/2024" and don't match their original review dates on MCITCentral. Could this be the date that these reviews were added to the MyMCIT database?

If this was a deliberate design decision, feel free to archive this issue. 🙂 Otherwise, I think it's helpful to see the actual date of a review as I personally value newer reviews of a course.

Example:
![CleanShot 161426](https://github.com/MyMCIT/MyMCIT/assets/86090707/a8999294-cb83-4e4d-9b75-e90bc49f53ed)

**Comment by drkchn** [comment]
Hi @qu8n Good observation! Yes, I believe the date (1/24/24) is when the old reviews were added to the MyMCIT database.
